# .github/workflows/docker-publish.yml
name: Docker Build and Push

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]  # name from build.yml
    types:
      - completed

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/github-actions-demo:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/github-actions-demo:latest