name: Java CI Matrix Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  BUILD_DIR: build/libs

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2 # Limits the number of matrix jobs running at the same time
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [17, 21]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }} (Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}

      - name: Grant execute permission to Gradle wrapper (non-Windows)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build