name: Java CI + Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/github-actions-demo

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: build/libs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: ${{ env.BUILD_DIR }}/*.jar

  push:
    needs: build
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: build/libs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: ${{ env.BUILD_DIR }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ env.IMAGE_NAME }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest, ${{ github.ref_name }}-${{ github.sha }}
