name: Java CI + Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/github-actions-demo
  BUILD_DIR: build/libs

jobs:
  build-and-push:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission to Gradle wrapper (non-Windows)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Log in to Docker Hub (Linux only)
        if: runner.os == 'Linux'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image (Linux only)
        if: runner.os == 'Linux'
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ env.IMAGE_NAME }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest, ${{ github.ref_name }}-${{ github.sha }}
